package main

import (
	"fmt"
)

/*
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
func main() {
	max := 4000000
	sum := 0

	for numOne, numTwo := 0, 1; numOne < max && numTwo < max; numOne, numTwo = numTwo, numTwo+numOne {
		if numTwo%2 == 0 {
			sum += numTwo
		}
	}
	fmt.Printf("Sum of all fibanocci numbers less than 4 million is %d\n", sum)
}
