/*
Pentagon numbers
Problem 44

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?
*/

package main

func genP(index int) int {
	return (3*index - 1) / 2
}

func main() {
	var pentagonalNumbers []int
	found := false
	for index := 0; found == true; index++ {
		genPN := genP(index)
		pentagonalNumbers = append(pentagonalNumbers, genPN)
		for _, pNum := range pentagonalNumbers {
			sum := pNum + genPN
			isSumP := isPentagonal(sum)
			if isSumP {
				sub := genPN - pNum
				isSubP := isPentagonal(sub)

			}
		}
	}
}

func isPentagonal(num int) bool {
	checkDivBy3 := num*2 + 1
	return checkDivBy3%3 == 0
}
